## Mod Properties
mod_id=pedestals
mod_name=Pedestals
mod_license=All Rights Reserved
mod_version=1.20.1-1.2
mod_group_id=net.mattias.pedestals
mod_authors=Mattias15
mod_description=Display your precious items with Pedestals!

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.6
forge_version_range=[47,)
loader_version_range=[47,)
#mapping_channel=official
#mapping_version=1.20.1
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
registrate_version=MC1.20-1.3.3